services:
  frontend:
    build:
      context: ./frontend  # Path to the Dockerfile for the React frontend
      dockerfile: Dockerfile  # Ensure this is the name of your Dockerfile
    container_name: cryptoseer-frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"
    ports:
      - "3000:3000"  # Map the container port 3000 to host port 3000
    networks:
      - app-tier
    restart: unless-stopped

  pocketbase:
    build: ./pocketbase # Path to the Dockerfile for PocketBase
    container_name: cryptoseer-pocketbase
    working_dir: /app
    ports:
      - "8090:8090"
    networks:
      - app-tier
    restart: unless-stopped
    volumes:
      - ./pocketbase_data:/app/pb_data  # Persistent storage for PocketBase

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KXQDTu5XrbsVDhe
      POSTGRES_DB: fillmore
    ports:
      - "5433:5432"
    networks:
      - app-tier
    volumes:
      - ./postgres:/var/lib/postgresql/data
    container_name: cryptoseer-postgres
    restart: unless-stopped


  backend:
    build: ./backend
    image: src/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://postgres:KXQDTu5XrbsVDhe@postgres:5432/fillmore"
      TF_ENABLE_ONEDNN_OPTS: 0
      POCKETBASE_URL: "http://pocketbase:8090"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - pocketbase
    container_name: cryptoseer-backend
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge